# Puerto dinámico para el servidor (Railway asigna uno automáticamente)
server.port=${PORT:8080}

# Configuración de conexión usando los nombres exactos de Railway
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate actualizará la estructura de las tablas si hay cambios en tus entidades
spring.jpa.hibernate.ddl-auto=update